config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      put "like", to: "articles#upvote"
    end
  end
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :contacts, only: [:new, :create]

  match '*path' => redirect('/'), via: :get
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end
  
  root to: 'pages#landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_votable
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  before_create -> (article) do
    article.slug = article.title.parameterize
  end

  validates_presence_of :title, :body, :image_link
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :message
  attribute :nickname, captcha: true

  def headers
    {
      subject: "Contact Form",
      to: "dev.shimolkhan@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: %i[ show edit update destroy upvote]
  before_action :authenticate_user!, except: [:index, :show, :upvote]

  def index
    @articles = Article.all.order('created_at DESC').where(["title ilike ?", "%#{params[:search]}%"])
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote 
    @article.upvote_by current_or_guest_user
    redirect_back fallback_location: root_path
  end 

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :image_link, :user_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else 
      flash.now[:error] = 'Cannot send Message!'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @articles = Article.all.limit(6)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
    flash[:alert] = "registration_is_not_allowed"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
					<form id="contact-form" class="contact-form" data-toggle="validator" novalidate="true">
						<div class="form-group">
							<%= f.input :title,
                          placeholder: 'Title',
                          label: false,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "title", class: "input input__icon form-control" } %>
						</div>

						<div class="form-group">
							<%= f.input :body,
                          placeholder: 'Description',
                          label: false,
                          required: true,
                          autofocus: true,
                          input_html: {  class: "input input__icon form-control", cols:"40", rows: "20"},
                          as: :trix_editor
                          %>
						</div>

						<div class="form-group">
							<%= f.input :image_link,
                          placeholder: 'Image URL',
                          label: false,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "image_link", class: "input input__icon form-control" } %>
						</div>

            <%= f.association :user, as: :hidden %>

						<div class="form-group">
							<%= f.button :submit, "Save", :class=>"btn" %>
              <%= link_to "Back", articles_path, :class=>"btn"%>
						</div>
				</div>
			</div>
			</form>
			<% end %>

app/views/articles/edit.html.erb
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<div class="col-lg-10">
			<div class="box shadow pb-0 p-5">
				<div class="content">
					<h2 class="title title--h3">
						<%= link_to root_path, :method => :get do %>
							<i class="fas fa-angle-left link pr-1"></i>
						<% end %>
					  Edit Article
					</h2>
					<%= render 'form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div id="articles">
<div class="container-fluid pt-3">
  <div>
    <div>
      <%= link_to root_path do %>
        <button class="btn mr-2">
          <i class="fas fa-arrow-circle-left link-white"></i>
        </button>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to new_article_path do %>
          <button class="btn mr-2">
            <i class="fas fa-arrow-circle-right link-white"></i>
          </button>
        <% end %>
      <% end %>

      <span class="text-muted">Browse All Articles</span>
        <div class="float-right">
          <%= form_tag articles_path, method: :get do %>
            <%= text_field_tag :search,
              params[:search],
              :class=>'input input__icon form-control',
              :style=>"border: 1px solid #82B1FF",
              placeholder:'Search Article' %>
          <% end %>
        </div>
      </div>
    </div>
    	<div class="row justify-content-center pt-3 mt-5">
    <% @articles.each do |article| %>
      <div class="col-md-4">
        <div class="card">
          <%= image_tag(article.image_link, :class=>"card-img-top")%>
          <div class="card-body">
            <span class="h5"><%= article.title %></span><br>
            <span class="text-muted"><%= article.created_at.strftime("%B, %d, %Y") %></span><br>
            <div class="d-flex flex-row justify-content-between align-items-center">
                <div>
                  <%= link_to "Browse", article, :class=>"btn mt-2"%>
                </div>
                <div>
                  <i class="fas fa-heart ml-2"><span class="ml-1"><%= article.get_upvotes.size %></span></i>
                </div>
            </div>
          </div>
        </div>
        <br>
      </div>
    <% end %>
	</div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container h-100">
	<div class="row h-100 justify-content-center align-items-center">
		<div class="col-lg-10">
			<div class="box shadow pb-0 p-5">
				<div class="content">
					<h2 class="title title--h3">
						<%= link_to root_path, :method => :get do %>
							<i class="fas fa-angle-left link pr-1"></i>
						<% end %>
					  Write New Article
					</h2>
					<%= render 'form', article: @article %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="scroll-line"></div>

<main class="main">
	<div class="container gutter-top">
		<div class="row sticky-parent">
			<!-- Sidebar -->
			<aside class="col-12 col-md-12 col-xl-3">
					<div class="sidebar box shadow pb-0 sticky-column">
						<svg class="avatar avatar--180" viewBox="0 0 188 188">
							<g class="avatar__box">
								<image xlink:href="https://i.imgur.com/KB0NSMP.jpg" height="100%" width="100%" />
							</g>
						</svg>
						<div class="text-center">
							<h3 class="title title--h3 sidebar__user-name">Shimol <span class="weight--500">Khan</span></h3>
							<div class="badge badge--light">Software Developer</div>

							<!-- Social -->
							<div class="social">
								<a class="social__link" href="https://www.facebook.com/shimolkhan.alive/" target="_blank"><i class="fab fa-facebook-f"></i></a>
								<a class="social__link" href="https://www.instagram.com/shimolkhan.dev/" target="_blank"><i class="fab fa-instagram"></i></a>
								<a class="social__link" href="https://twitter.com/dev_shimolkhan" target="_blank"><i class="fab fa-twitter"></i></a>
								<a class="social__link" href="https://www.linkedin.com/in/shimol-khan/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
								<a class="social__link" href="https://github.com/Shimol-Khan" target="_blank"><i class="fab fa-github"></i></a>
							</div>
						</div>

						<div class="sidebar__info box-inner box-inner--rounded">
							<ul class="contacts-block">
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Birthday">
									<i class="fas fa-birthday-cake mr-3"></i>October 26, 1994
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Address">
									<i class="fas fa-map-marker-alt mr-3"></i>Kuala Lumpur, Malaysia
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="E-mail">
									<a href="mailto:example@mail.com"><i class="fas fa-envelope mr-3"></i>shimolkhan.dev@gmail.com</a>
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Phone">
									<i class="fas fa-mobile mr-3"></i>+60 (111) 67-53-634
								</li>
							</ul>

							<%= link_to "/shimol-khan-resume-v6.pdf", :class=>"btn", target: "_blank" do %>
								<i class="far fa-arrow-alt-circle-down mr-1"></i> Download Resume
							<% end %>

							<div class="d-flex mt-3 justify-content-center">
								<% if user_signed_in? %>
									<div class="mr-2">
										<%= link_to "Logout", destroy_user_session_path, method: :delete, :class=>"link" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</aside>

			<!-- Content -->
			<div class="col-12 col-md-12 col-xl-9">
				<div class="box shadow pb-0">
					<!-- Post -->
					<div class="pb-3">
						<header class="header-post">
							<div class="header-post__date">
								<div class="float-left">
								<%= link_to articles_path, :method => :get do %>
									<i class="fas fa-arrow-left fa-2x link pr-1"></i>
								<% end %>
								</div>
								<%= @article.created_at.strftime("%B, %d, %Y")%>
							</div>
							<h1 class="title title--h1">
								<%= @article.title %>
							</h1>
							<div class="header-post__image-wrap">
								<%= image_tag(@article.image_link, :class=>"cover lazyload")%>
							</div>
						</header>
						<div class="caption-post">
							<p class="text-justify"><%= sanitize @article.body %></p>
						</div>

						<footer class="footer-post text-center">
							<p>Shimol Khan
							</p>
						</footer>

						<!------------------------------ Vote ---------------------------->
						<div class="text-center">
							<% if !current_or_guest_user.voted_for? @article %>
								<p>Like this Article?</p>
								<%= link_to like_article_path(@article), method: :put do %>
									<button class="btn">
										<i class="far fa-heart"></i>
									</button>
								<% end %>
							<% end %>
						</div>
            <!-----------------------------/ Vote ---------------------------->

						<% if user_signed_in? %>
              <div class="text-center mt-3">
                <%= link_to "Create New", new_article_path, :class=>"link"%>
                <%= link_to "Edit", edit_article_path, :class=>"mx-3 link"%>
                <%= link_to "Delete", article_path, method: :delete, data:{confirm: 'Are you sure?'}, :class=>"link"%>
              </div>
						<% end %>
					</div>
					</div>
					<footer class="footer">Site Engineered By <a href="https://github.com/kiiilllerbot" target="_blank">Shimol Khan</a> With <i class="far fa-heart"></i></footer>
				</div>
			</div>
		</div>
	</div>
</main>

<div class="back-to-top"></div>

<!-- SVG masks -->
<svg class="svg-defs">
	<clipPath id="avatar-box">
		<path
			d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z" />
	</clipPath>
	<clipPath id="avatar-hexagon">
		<path
			d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z" />
	</clipPath>
</svg>

app/views/contacts/create.html.erb
<% content_for :title do %>
  Congrats
<% end %>
<div class="scroll-line"></div>

<main class="main">
	<div class="container gutter-top">
		<div class="row sticky-parent">
			<!-- Sidebar -->
			<aside class="col-12 col-md-12 col-xl-3">
					<div class="sidebar box shadow pb-0 sticky-column">
						<svg class="avatar avatar--180" viewBox="0 0 188 188">
							<g class="avatar__box">
								<image xlink:href="https://i.imgur.com/KB0NSMP.jpg" height="100%" width="100%" />
							</g>
						</svg>
						<div class="text-center">
							 <h3 class="title title--h3 sidebar__user-name">Shimol<span class="weight--500"> Khan</span></h3>
							<div class="badge badge--light">Ruby on Rails Developer</div>

							<!-- Social -->
							<div class="social">
								<a class="social__link" href="https://www.facebook.com/kiiilllerbot/" target="_blank"><i class="fab fa-facebook-f"></i></a>
								<a class="social__link" href="https://www.instagram.com/kiiilllerbot/" target="_blank"><i class="fab fa-instagram"></i></a>
								<a class="social__link" href="https://twitter.com/kiiilllerbot" target="_blank"><i class="fab fa-twitter"></i></a>
								<a class="social__link" href="https://www.linkedin.com/in/kiiilllerbot/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
								<a class="social__link" href="https://github.com/kiiilllerbot" target="_blank"><i class="fab fa-github"></i></a>
							</div>
						</div>

						<div class="sidebar__info box-inner box-inner--rounded">
							<ul class="contacts-block">
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Birthday">
									<i class="fas fa-birthday-cake mr-3"></i>October 26, 1994
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Address">
									<i class="fas fa-map-marker-alt mr-3"></i>Kuala Lumpur, Malaysia
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="E-mail">
									<a href="mailto:example@mail.com"><i class="fas fa-envelope mr-3"></i>dev.shimolkhan@gmail.com</a>
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Phone">
									<i class="fas fa-mobile mr-3"></i>+60 (17) 4216716
								</li>
							</ul>

							<%= link_to "/shimol-khan-resume-v6.pdf", :class=>"btn", target: "_blank" do %>
								<i class="far fa-arrow-alt-circle-down mr-1"></i> Download Resume
							<% end %>

							<div class="d-flex mt-3 justify-content-center">
								<% if user_signed_in? %>
									<div class="mr-2">
										<%= link_to "Logout", destroy_user_session_path, method: :delete, :class=>"link" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</aside>

			<!-- Content -->
			<div class="col-12 col-md-12 col-xl-9">
				<div class="box shadow pb-0">
					<!-- Post -->
					<div class="pb-3">
						<header class="header-post">
							<div class="header-post__date">
								<div class="float-left">
								<%= link_to root_path, :method => :get do %>
									<i class="fas fa-arrow-left link pr-1"></i>
								<% end %>
								</div>
								CONTACT
							</div>
							<h1 class="title title--h1">Greeting!</h1>
						</header>
          <p>I have collected your Message!</p>
          <hr class="my-3">
          <p>Thanks for contacting me. I will contact you back soon.</p>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

<div class="back-to-top"></div>

<!-- SVG masks -->
<svg class="svg-defs">
	<clipPath id="avatar-box">
		<path
			d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z" />
	</clipPath>
	<clipPath id="avatar-hexagon">
		<path
			d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z" />
	</clipPath>
</svg>

app/views/contacts/new.html.erb
<div class="scroll-line"></div>

<main class="main mb-5">
	<div class="container gutter-top">
		<div class="row sticky-parent">
			<!-- Sidebar -->
			<aside class="col-12 col-md-12 col-xl-3">
					<div class="sidebar box shadow pb-0 sticky-column">
						<svg class="avatar avatar--180" viewBox="0 0 188 188">
							<g class="avatar__box">
								<image xlink:href="https://i.imgur.com/KB0NSMP.jpg" height="100%" width="100%" />
							</g>
						</svg>
						<div class="text-center">
							<h3 class="title title--h3 sidebar__user-name">Shimol<span class="weight--500"> Khan</span></h3>
							<div class="badge badge--light">Ruby on Rails Developer</div>

							<!-- Social -->
							<div class="social">
								<a class="social__link" href="https://www.facebook.com/kiiilllerbot/" target="_blank"><i class="fab fa-facebook-f"></i></a>
								<a class="social__link" href="https://www.instagram.com/kiiilllerbot/" target="_blank"><i class="fab fa-instagram"></i></a>
								<a class="social__link" href="https://twitter.com/kiiilllerbot/" target="_blank"><i class="fab fa-twitter"></i></a>
								<a class="social__link" href="https://www.linkedin.com/in/kiiilllerbot/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
								<a class="social__link" href="https://github.com/kiiilllerbot" target="_blank"><i class="fab fa-github"></i></a>
							</div>
						</div>

						<div class="sidebar__info box-inner box-inner--rounded">
							<ul class="contacts-block">
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Birthday">
									<i class="fas fa-birthday-cake mr-3"></i>October 26, 1994
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Address">
									<i class="fas fa-map-marker-alt mr-3"></i>Kuala Lumpur, Malaysia
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="E-mail">
									<a href="mailto:example@mail.com"><i class="fas fa-envelope mr-3"></i>dev.shimolkhan@gmail.com</a>
								</li>
								<li class="contacts-block__item" data-toggle="tooltip" data-placement="top" title="Phone">
									<i class="fas fa-mobile mr-3"></i>+60 (17) 4216716
								</li>
							</ul>

							<%= link_to "/shimol-khan-resume-v6.pdf", :class=>"btn", target: "_blank" do %>
								<i class="far fa-arrow-alt-circle-down mr-1"></i> Download Resume
							<% end %>

							<div class="d-flex mt-3 justify-content-center">
								<% if user_signed_in? %>
									<div class="mr-2">
										<%= link_to "Logout", destroy_user_session_path, method: :delete, :class=>"link" %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</aside>

			<!-- Content -->
			<div class="col-12 col-md-12 col-xl-9">
				<div class="box shadow pb-0">
					<!-- Post -->
					<div class="pb-3">
						<header class="header-post">
							<div class="header-post__date">
								<div class="float-left">
								<%= link_to root_path, :method => :get do %>
									<i class="fas fa-arrow-left link pr-1"></i>
								<% end %>
								</div>
								CONTACT
							</div>
						</header>
						<div class="map" id="map">
						<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d15926.401320114233!2d101.5361837!3d3.678057!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2smy!4v1624123550440!5m2!1sen!2smy" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
						</div>
            <%= simple_form_for @contact, :class=>"contact-form" do |f| %>
								<form id="contact-form" class="contact-form" data-toggle="validator">
									<div class="row">
										<div class="form-group col-12 col-md-6">
											<%= f.input :name,
												label: false,
												placeholder: 'Full Name',
												input_html:{class:"input input__icon form-control"}
											%>
										</div>

										<div class="form-group col-12 col-md-6">
											<%= f.input :email,
												label: false,
												placeholder: 'Email Address',
												input_html:{class:"input input__icon form-control"}
											%>
										</div>
										<div class="form-group col-12 col-md-12">
                    	<%= f.input :message,
												label: false,
												placeholder: 'Your Message',
												input_html:{class:"textarea form-control", rows: 5},
                        as: :text
											%>
										</div>
                    <%= f.input :nickname, as: :hidden %>
									</div>
									<div class="row">
										<div class="col-12 col-md-6 order-2 order-md-1 text-center text-md-left">
											<div id="validator-contact" class="hidden"></div>
										</div>
										<div class="col-12 col-md-6 order-1 order-md-2 text-right">
                    <%= f.button :submit, "Send Message", :class=>"btn"%>
										</div>
									</div>
								</form>
								<% end %>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

<div class="back-to-top"></div>

<!-- SVG masks -->
<svg class="svg-defs">
	<clipPath id="avatar-box">
		<path
			d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z" />
	</clipPath>
	<clipPath id="avatar-hexagon">
		<path
			d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z" />
	</clipPath>
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shimol Khan > Code Is Love</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('brand.png') %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body class="bg-triangles">
    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<!---------------------- Preloader -------------------->
  <%= render 'shared/preloader' %>
<!---------------------/ Preloader -------------------->

<!------------------------ Main ----------------------->
  <%= render 'shared/main' %>
<!------------------------/ Main ---------------------->

<!------------------------ Footer --------------------->
  <%= render 'shared/footer' %>
<!-----------------------/ Footer --------------------->

app/views/shared/_footer.html.erb
<div class="back-to-top"></div>
<svg class="svg-defs">
  <clipPath id="avatar-box">
    <path d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z"/>
  </clipPath>
  <clipPath id="avatar-hexagon">
    <path d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z"/>
  </clipPath>		
</svg>

app/views/shared/_preloader.html.erb
<div class="preloader">
	<div class="preloader__wrap">
		<div class="circle-pulse">
      <div class="circle-pulse__1"></div>
      <div class="circle-pulse__2"></div>
    </div>
		<div class="preloader__progress"><span></span></div>
	</div>
</div>